# package.yaml
name:                hlox
version:             0.1.0.0
license:             BSD-3-Clause
author:              "Your Name"
maintainer:          "your.email@example.com"

extra-source-files:
   - README.md

library:
  exposed-modules:
    - Token
    - Scanner
    - Lox
  source-dirs:
    - src
  dependencies:
    - base >=4.7 && <5
  language: Haskell2010

executables:
  hlox:
    main:                Main.hs
    source-dirs:
      - app
    dependencies:
      - hlox
      - base >=4.7 && <5
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    language: Haskell2010
