# package.yaml
name:                hlox
version:             0.1.0.0
license:             BSD-3-Clause
author:              "chris rectenwald"
maintainer:          "cdrectenwald@example.com"

extra-source-files:
   - README.md

library:
  exposed-modules:
    - Token
    - Scanner
    - Lox
    - Parser
    - Interpreter
    - Environment
    - Expr
  source-dirs:
    - src
  dependencies:
    - base >=4.7 && <5
    - mtl
    - containers
  language: Haskell2010

executables:
  hlox:
    main:                Main.hs
    source-dirs:
      - app
    dependencies:
      - hlox
      - base >=4.7 && <5
      - mtl
      - containers
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    language: Haskell2010

tests:
  hlox-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hlox
      - base >=4.7 && <5
      - hspec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
